### PR TITLE
[WIP] Add super basic man pages

### PR DESCRIPTION
**Pull request by johnisom**
This adds super simple man pages. To test this out, first *install the npm package* (`sudo npm install -g .` on maestro root) and try any of the following:

```
man maestro
man maestro-get-templates
man maestro-help
man maestro-deploy
man maestro-new
man maestro-teardown
```

This is still a WIP because I need to add a simple man page for `maestro-configure`. This will be done when a PR for that feature is opened.

**NOTE**: this is to be merged into the `npm-packaging` branch

### CODE REVIEW

**Comment by johnisom** [comment]
I still need to rebase this so it's based off of `npm-packaging`, not off of `new-command` and `templates`.

**Comment by johnisom** [comment]
So in reality, this really starts at bf4a035

**Comment by johnisom** [comment]
OK, I successfully rebased this branch!

**Comment by zklamm** [comment]
I'd like to discuss these changes before merging them in.

**Comment by johnisom** [comment]
@zklamm for sure. I'm still working on this, and since these are docs from the whole team, I'd love everybody's input and contributions. Feel more than free to work on this branch as well

**Comment by johnisom** [comment]
Oh, just by the way, the name `maestro` on npm isn't really taken--it's a security holding package (placeholder dummy) which means they will give it to you upon request. I've already sen't an email asking about it, so hopefully I hear back soon and we can claim that name.

**Comment by johnisom** [comment]
For now I will tentatively merge this in, but development on this branch should still take place.

**Pull request merged**
